; Heltec WiFi LoRa 32 V2 + SIM808 (GNSS) + OLED integrada
; Documentación de PlatformIO: https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_V2]
; espressif32 6.9.0 incluye framework-arduinoespressif32 2.0.17 (Arduino-ESP32 2.x).
platform = espressif32@6.9.0
board = heltec_wifi_lora_32_V2
framework = arduino

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
upload_speed = 921600

build_flags =
    -Wall
    -Wextra

lib_deps =
    thingpulse/ESP8266 and ESP32 OLED driver for SSD1306 displays@^4.6.1
